project:
  type: website
  output-dir: docs

website:
  title: "Yuan Zhou"
  navbar:
    left:
      - text: Welcome!
        file: index.qmd
      - text: About Me 
        file: about.qmd
      - text: Certificates
        file: certificates.qmd
      - text: Academic Projects
        file: academic_projects.qmd
      - text: Blog
        href: https://zwhyggy.github.io/Blog/
      - text: Personal
        file: Other.qmd
    
      


format:
  html:
    theme: sketchy
    css: styles.css
    toc: true
    page-layout: full

editor: visual


