project:
  type: website
  output-dir: docs

website:
  title: "Yuan Zhou"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents: 
          - about.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual


