project:
  type: website
  output-dir: docs

website:
  title: "Yuan Zhou"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Projects 
        file: about.qmd
  sidebar: 
    style: docked

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true
    page-layout: full

editor: visual


