project:
  type: website
  output-dir: docs

website:
  title: "mysite"
  navbar:
    left:
      - text: Welcome!
        file: index.qmd
      - text: About Me 
        file: about.qmd


format:
  html:
    theme: sketchy
    css: styles.css
    toc: true
    page-layout: full

editor: visual


